# Generated by Django 4.2.2 on 2023-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_ts', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('event_name', models.CharField(max_length=255)),
            ],
        ),
    ]
